import type { Artwork } from "@/types/artwork";

export const ARTWORKS: Artwork[] = [
  {
    id: "faro-nocturno",
    title: "Faro Nocturno",
    artist: "Desconocido",
    year: 2026,
    difficulty: "intermediate",
    duration_min: 80,
    color: "#1a1a2e",
    image: "/artworks/Faro Nocturno.png",
    tags: ["faro", "noche", "marino", "paisaje"],
    stages: [
      {
        number: 1,
        title: "Base Amarilla",
        description: "Cubre la base con amarillo para crear la iluminación del faro.",
        duration_min: 20,
        image: "/artworks/FARO-NOCTURNO-DIVISIONES/ETAPA #1 - Amarillo.png",
      },
      {
        number: 2,
        title: "Capas Naranjas",
        description: "Añade tonos naranjas para la calidez de la luz.",
        duration_min: 20,
        image: "/artworks/FARO-NOCTURNO-DIVISIONES/ETAPA #2 - Naranja.png",
      },
      {
        number: 3,
        title: "Cielo Azul",
        description: "Pinta el cielo nocturno con azul profundo.",
        duration_min: 20,
        image: "/artworks/FARO-NOCTURNO-DIVISIONES/ETAPA #3 - Azul.png",
      },
      {
        number: 4,
        title: "Detalles Negros",
        description: "Completa con detalles en negro para contraste y definición.",
        duration_min: 20,
        image: "/artworks/FARO-NOCTURNO-DIVISIONES/ETAPA #4 - Negro.png",
      },
    ],
  },
  {
    id: "flores-blancas",
    title: "Flores Blancas",
    artist: "Desconocido",
    year: 2026,
    difficulty: "beginner",
    duration_min: 75,
    color: "#f5f5f5",
    image: "/artworks/Flores Blancas.png",
    tags: ["flores", "blancas", "naturaleza", "suave"],
    stages: [
      {
        number: 1,
        title: "Base Naranja",
        description: "Establece la base con tonos naranjas para los pétalos.",
        duration_min: 15,
        image: "/artworks/FLORES-BLANCAS-DIVISIONES'/Etapa #1 - Naranja.png",
      },
      {
        number: 2,
        title: "Tonos Crema",
        description: "Añade crema suave para las flores principales.",
        duration_min: 20,
        image: "/artworks/FLORES-BLANCAS-DIVISIONES'/Etapa #2 - Crema Suave.png",
      },
      {
        number: 3,
        title: "Follaje Verde",
        description: "Pinta las hojas y tallos en verde.",
        duration_min: 20,
        image: "/artworks/FLORES-BLANCAS-DIVISIONES'/Etapa #3 - Verde  .png",
      },
      {
        number: 4,
        title: "Fondo Beige",
        description: "Completa con fondo beige arena para enmarcar el arreglo.",
        duration_min: 20,
        image: "/artworks/FLORES-BLANCAS-DIVISIONES'/Etapa 4 - Fondo Beige Arena .png",
      },
    ],
  },
  {
    id: "mujer-sombrero",
    title: "Mujer en un Sombrero",
    artist: "Desconocido",
    year: 2026,
    difficulty: "intermediate",
    duration_min: 85,
    color: "#8B4513",
    image: "/artworks/MUJER EN UN SOMBRERO.jpg",
    tags: ["retrato", "mujer", "sombrero", "moda"],
    stages: [
      {
        number: 1,
        title: "Contornos Base",
        description: "Define los contornos principales de la figura y el sombrero.",
        duration_min: 17,
        image: "/artworks/MUJER-EN-UN-SOMBRERO-DIVISIONES/Etapa 1.png",
      },
      {
        number: 2,
        title: "Tonos Base",
        description: "Aplica los tonos base para piel y ropa.",
        duration_min: 17,
        image: "/artworks/MUJER-EN-UN-SOMBRERO-DIVISIONES/Etapa 2.png",
      },
      {
        number: 3,
        title: "Detalles del Sombrero",
        description: "Pinta los detalles característicos del sombrero.",
        duration_min: 17,
        image: "/artworks/MUJER-EN-UN-SOMBRERO-DIVISIONES/Etapa 3.png",
      },
      {
        number: 4,
        title: "Sombras y Luz",
        description: "Añade sombras para profundidad y realismo.",
        duration_min: 17,
        image: "/artworks/MUJER-EN-UN-SOMBRERO-DIVISIONES/Etapa 4.png",
      },
      {
        number: 5,
        title: "Detalles Finales",
        description: "Completa con detalles finos y retoques finales.",
        duration_min: 17,
        image: "/artworks/MUJER-EN-UN-SOMBRERO-DIVISIONES/Etapa 5.png",
      },
    ],
  },
  {
    id: "tucan-tropical",
    title: "Tucán Tropical",
    artist: "Desconocido",
    year: 2026,
    difficulty: "advanced",
    duration_min: 95,
    color: "#00AA00",
    image: "/artworks/Tucan Tropical.png",
    tags: ["tucán", "tropical", "fauna", "colorido"],
    stages: [
      {
        number: 1,
        title: "Base Azul Oscuro",
        description: "Cubre la base con azul oscuro para el fondo de la selva.",
        duration_min: 19,
        image: "/artworks/TUCAN-TROPICAL-DIVISIONES/Etapa #1 - Azul Oscuro.png",
      },
      {
        number: 2,
        title: "Tonos Crema",
        description: "Aplica crema para el pecho del tucán.",
        duration_min: 19,
        image: "/artworks/TUCAN-TROPICAL-DIVISIONES/Etapa 2 - Crema .png",
      },
      {
        number: 3,
        title: "Pico Naranja",
        description: "Pinta el distintivo pico del tucán en naranja vibrante.",
        duration_min: 19,
        image: "/artworks/TUCAN-TROPICAL-DIVISIONES/Etapa #3 - Naranja.png",
      },
      {
        number: 4,
        title: "Plumaje Verde",
        description: "Añade el verde del plumaje característico.",
        duration_min: 19,
        image: "/artworks/TUCAN-TROPICAL-DIVISIONES/Etapa #4 - Verde.png",
      },
      {
        number: 5,
        title: "Fondo y Detalles",
        description: "Completa con fondo cian y detalles finales.",
        duration_min: 19,
        image: "/artworks/TUCAN-TROPICAL-DIVISIONES/Etapa #5 - Fondo Cian (1).png",
      },
    ],
  },
];

export const DIFFICULTY_LABEL: Record<string, string> = {
  beginner:     "Principiante",
  intermediate: "Intermedio",
  advanced:     "Avanzado",
};

export const DIFFICULTY_COLOR: Record<string, string> = {
  beginner:     "text-emerald-400 border-emerald-400/40 bg-emerald-400/10",
  intermediate: "text-amber-400 border-amber-400/40 bg-amber-400/10",
  advanced:     "text-red-400 border-red-400/40 bg-red-400/10",
};
