"""Seed the database with the artwork catalog."""
from sqlalchemy.ext.asyncio import AsyncSession
from app.models.artwork import Artwork

ARTWORKS = [
    dict(
        id="faro-nocturno",
        title="Faro Nocturno",
        artist="Desconocido",
        year=2026,
        difficulty="intermediate",
        duration_min=80,
        color="#1a1a2e",
        image="/artworks/Faro Nocturno.png",
        tags=["faro", "noche", "marino", "paisaje"],
        stages=[
            {
                "number": 1,
                "title": "Base Amarilla",
                "description": "Cubre la base con amarillo para crear la iluminación del faro.",
                "duration_min": 20,
                "image": "/artworks/FARO-NOCTURNO-DIVISIONES/ETAPA #1 - Amarillo.png",
                "colors": ["Amarillo Cálido", "Amarillo Limón"],
                "materials": ["Pintura acrílica amarilla", "Agua"],
                "brushes": ["Brocha plana mediana", "Esponja"],
                "objective": "Establecer la base luminosa que representará la luz del faro",
            },
            {
                "number": 2,
                "title": "Capas Naranjas",
                "description": "Añade tonos naranjas para la calidez de la luz.",
                "duration_min": 20,
                "image": "/artworks/FARO-NOCTURNO-DIVISIONES/ETAPA #2 - Naranja.png",
                "colors": ["Naranja Quemado", "Naranja Claro"],
                "materials": ["Pintura acrílica naranja", "Agua"],
                "brushes": ["Brocha redonda mediana", "Difusor"],
                "objective": "Añadir capas de transición del amarillo hacia tonos más cálidos",
            },
            {
                "number": 3,
                "title": "Cielo Azul",
                "description": "Pinta el cielo nocturno con azul profundo.",
                "duration_min": 20,
                "image": "/artworks/FARO-NOCTURNO-DIVISIONES/ETAPA #3 - Azul.png",
                "colors": ["Azul Marino", "Azul Profundo"],
                "materials": ["Pintura acrílica azul", "Agua"],
                "brushes": ["Brocha plana grande", "Rodillo"],
                "objective": "Crear el contraste nocturno alrededor de la luz del faro",
            },
            {
                "number": 4,
                "title": "Detalles Negros",
                "description": "Completa con detalles en negro para contraste y definición.",
                "duration_min": 20,
                "image": "/artworks/FARO-NOCTURNO-DIVISIONES/ETAPA #4 - Negro.png",
                "colors": ["Negro Profundo", "Gris Oscuro"],
                "materials": ["Pintura acrílica negra", "Agua"],
                "brushes": ["Brocha fina pequeña", "Pincel de punta"],
                "objective": "Añadir detalles y definición final al estructura del faro",
            },
        ],
    ),
    dict(
        id="flores-blancas",
        title="Flores Blancas",
        artist="Desconocido",
        year=2026,
        difficulty="beginner",
        duration_min=75,
        color="#f5f5f5",
        image="/artworks/Flores Blancas.png",
        tags=["flores", "blancas", "naturaleza", "suave"],
        stages=[
            {
                "number": 1,
                "title": "Base Naranja",
                "description": "Establece la base con tonos naranjas para los pétalos.",
                "duration_min": 15,
                "image": "/artworks/FLORES-BLANCAS-DIVISIONES/Etapa #1 - Naranja.png",
                "colors": ["Naranja Suave", "Durazno"],
                "materials": ["Pintura acrílica naranja", "Agua"],
                "brushes": ["Brocha esponja mediana"],
                "objective": "Crear la base cálida para los pétalos de las flores",
            },
            {
                "number": 2,
                "title": "Tonos Crema",
                "description": "Añade crema suave para las flores principales.",
                "duration_min": 20,
                "image": "/artworks/FLORES-BLANCAS-DIVISIONES/Etapa #2 - Crema Suave.png",
                "colors": ["Crema Suave", "Blanco Cálido"],
                "materials": ["Pintura acrílica crema", "Agua"],
                "brushes": ["Brocha redonda mediana", "Difusor suave"],
                "objective": "Añadir las flores principales con tonos claros",
            },
            {
                "number": 3,
                "title": "Follaje Verde",
                "description": "Pinta las hojas y tallos en verde.",
                "duration_min": 20,
                "image": "/artworks/FLORES-BLANCAS-DIVISIONES/Etapa #3 - Verde  .png",
                "colors": ["Verde Fresco", "Verde Oscuro"],
                "materials": ["Pintura acrílica verde", "Agua"],
                "brushes": ["Brocha fina pequeña", "Pincel de punta aguda"],
                "objective": "Pintar hojas y tallos para crear estructura natural",
            },
            {
                "number": 4,
                "title": "Fondo Beige",
                "description": "Completa con fondo beige arena para enmarcar el arreglo.",
                "duration_min": 20,
                "image": "/artworks/FLORES-BLANCAS-DIVISIONES/Etapa 4 - Fondo Beige Arena .png",
                "colors": ["Beige Arena", "Gris Claro"],
                "materials": ["Pintura acrílica beige", "Agua"],
                "brushes": ["Brocha plana grande"],
                "objective": "Completar el fondo para enmarcar las flores",
            },
        ],
    ),
    dict(
        id="mujer-sombrero",
        title="Mujer en un Sombrero",
        artist="Desconocido",
        year=2026,
        difficulty="intermediate",
        duration_min=85,
        color="#8B4513",
        image="/artworks/MUJER EN UN SOMBRERO.jpg",
        tags=["retrato", "mujer", "sombrero", "moda"],
        stages=[
            {
                "number": 1,
                "title": "Contornos Base",
                "description": "Define los contornos principales de la figura y el sombrero.",
                "duration_min": 17,
                "image": "/artworks/MUJER-EN-UN-SOMBRERO-DIVISIONES/Etapa #1 - Azul oscuro.png",
                "colors": ["Azul Oscuro", "Gris Oscuro"],
                "materials": ["Pintura acrílica azul oscuro", "Agua"],
                "brushes": ["Brocha fina pequeña", "Pincel de punta"],
                "objective": "Establecer los contornos y estructura básica del retrato",
            },
            {
                "number": 2,
                "title": "Tonos Base",
                "description": "Aplica los tonos base para piel y ropa.",
                "duration_min": 17,
                "image": "/artworks/MUJER-EN-UN-SOMBRERO-DIVISIONES/Etapa #2 - Blanco.png",
                "colors": ["Blanco Cálido", "Ocre Suave"],
                "materials": ["Pintura acrílica blanca", "Tierra"],
                "brushes": ["Brocha redonda mediana", "Esponja"],
                "objective": "Aplicar los tonos base de piel y ropa",
            },
            {
                "number": 3,
                "title": "Detalles del Sombrero",
                "description": "Pinta los detalles característicos del sombrero.",
                "duration_min": 17,
                "image": "/artworks/MUJER-EN-UN-SOMBRERO-DIVISIONES/Etapa #3 - Verde.png",
                "colors": ["Verde Suave", "Blanco"],
                "materials": ["Pintura acrílica verde", "Agua"],
                "brushes": ["Brocha fina mediana", "Pincel redondo"],
                "objective": "Añadir detalles y texturas al sombrero",
            },
            {
                "number": 4,
                "title": "Sombras y Luz",
                "description": "Añade sombras para profundidad y realismo.",
                "duration_min": 17,
                "image": "/artworks/MUJER-EN-UN-SOMBRERO-DIVISIONES/Etapa #4 - Negro.png",
                "colors": ["Negro Profundo", "Marrón Oscuro"],
                "materials": ["Pintura acrílica negra", "Agua"],
                "brushes": ["Brocha fina pequeña", "Difusor"],
                "objective": "Crear sombras para añadir profundidad al retrato",
            },
            {
                "number": 5,
                "title": "Detalles Finales",
                "description": "Completa con detalles finos y retoques finales.",
                "duration_min": 17,
                "image": "/artworks/MUJER-EN-UN-SOMBRERO-DIVISIONES/ETAPA #5 - Morado.png",
                "colors": ["Morado Suave", "Blanco Brillante"],
                "materials": ["Pintura acrílica morada", "Agua"],
                "brushes": ["Pincel fino pequeño", "Pincel de punta aguda"],
                "objective": "Completar con detalles y retoques para el acabado final",
            },
        ],
    ),
    dict(
        id="tucan-tropical",
        title="Tucán Tropical",
        artist="Desconocido",
        year=2026,
        difficulty="advanced",
        duration_min=95,
        color="#00AA00",
        image="/artworks/Tucan Tropical.png",
        tags=["tucán", "tropical", "fauna", "colorido"],
        stages=[
            {
                "number": 1,
                "title": "Base Azul Oscuro",
                "description": "Cubre la base con azul oscuro para el fondo de la selva.",
                "duration_min": 19,
                "image": "/artworks/TUCAN-TROPICAL-DIVISIONES/Etapa #1 - Azul Oscuro.png",
                "colors": ["Azul Profundo", "Azul Marino"],
                "materials": ["Pintura acrílica azul oscuro", "Agua"],
                "brushes": ["Brocha plana grande", "Rodillo"],
                "objective": "Crear el fondo oscuro que representa la selva tropical",
            },
            {
                "number": 2,
                "title": "Tonos Crema",
                "description": "Aplica crema para el pecho del tucán.",
                "duration_min": 19,
                "image": "/artworks/TUCAN-TROPICAL-DIVISIONES/Etapa 2 - Crema .png",
                "colors": ["Crema Suave", "Amarillo Pálido"],
                "materials": ["Pintura acrílica crema", "Agua"],
                "brushes": ["Brocha redonda mediana", "Esponja"],
                "objective": "Pintar el pecho del tucán con tonos claros",
            },
            {
                "number": 3,
                "title": "Pico Naranja",
                "description": "Pinta el distintivo pico del tucán en naranja vibrante.",
                "duration_min": 19,
                "image": "/artworks/TUCAN-TROPICAL-DIVISIONES/Etapa #3 - Naranja.png",
                "colors": ["Naranja Vibrante", "Rojo Naranja"],
                "materials": ["Pintura acrílica naranja", "Agua"],
                "brushes": ["Brocha redonda pequeña", "Pincel de punta"],
                "objective": "Destacar el pico distintivo del tucán",
            },
            {
                "number": 4,
                "title": "Plumaje Verde",
                "description": "Añade el verde del plumaje característico.",
                "duration_min": 19,
                "image": "/artworks/TUCAN-TROPICAL-DIVISIONES/Etapa #4 - Verde.png",
                "colors": ["Verde Esmeralda", "Verde Oscuro"],
                "materials": ["Pintura acrílica verde", "Agua"],
                "brushes": ["Brocha fina mediana", "Pincel redondo"],
                "objective": "Pintar el plumaje característico del tucán",
            },
            {
                "number": 5,
                "title": "Fondo y Detalles",
                "description": "Completa con fondo cian y detalles finales.",
                "duration_min": 19,
                "image": "/artworks/TUCAN-TROPICAL-DIVISIONES/Etapa #5 - Fondo Cian (1).png",
                "colors": ["Cian Brillante", "Verde Agua"],
                "materials": ["Pintura acrílica cian", "Agua"],
                "brushes": ["Brocha plana grande", "Pincel fino"],
                "objective": "Completar con fondo y detalles finales del ave",
            },
        ],
    ),
]


async def seed_artworks(db: AsyncSession):
    for data in ARTWORKS:
        existing = await db.get(Artwork, data["id"])
        if not existing:
            db.add(Artwork(**data))
    await db.commit()
